;Dada uma matriz 2x2 na memória, calcule e exiba a sua matriz
;transposta.

.MODEL SMALL
.STACK 100H
.DATA

    MATRIZ DB 1 , 2
           DB 3 , 4    

    MATRIZ_TRANSPOSTA 2 DUP(2 DUP(?))

.CODE
MAIN PROC
    MOV AX, @DATA
    MOV DS, AX
    MOV ES AX
    
    CALL TRANSPOSTA

    MOV AH, 4CH
    INT 21H
MAIN ENDP

;TRANSPOR UMA MATRIZ 2X2 É BASICAMENTE TROCAR A DIAGONAL SECUNDÁRIA
;PROCEDIMENTO PARA TRANSPOSIÇÃO DE UMA MATRIZ 2X2
TRANSPOSTA PROC
    XOR BX, BX
    XOR SI, SI

    LEA SI, MATRIZ
    LEA DI, MATRIZ_TRANSPOSTA
    MOV CX, 4SSSSS
    MOVSB
    REP

    XOR BX, BX
    XOR SI, SI
    MOV AL, MATRIZ[BX][SI+1]
    MOV DL, MATRIZ[BX+1][SI]

    MOV MATRIZ_TRANSPOSTA[BX][SI+1], DL
    MOV MATRIZ_TRANSPOSTA[BX+1][SI], AL

    RET

TRANSPOSTA ENDP



END MAIN