MODEL SMALL
.DATA
VETOR DB 1, 1, 1, 2, 2, 2
.CODE
MAIN PROC
MOV AX, @DATA
MOV DS,AX

XOR DL, DL ;ZERA DL
MOV CX,6 ;INICIA CX COM VALOR 6
XOR BX, BX ;ZERA BX

VOLTA:
MOV DL, VETOR[BX] ;MOVE PARA DL A POSIÇÃO DESCRITA EM BX
INC BX ;INCREMENTA O VALOR DE BX, OU SEJA, VAI PARA O PROXIMO ELEMENTO DO VETOR
ADD DL, 30H ;CONVERTE O VALOR DE DL PARA ASCII


MOV AH, 02 ;IMPRIME O CARACTER EM DL
INT 21H

LOOP VOLTA ;LOOP ENQUANTO CX > 0

MOV AH,4CH
INT 21H ;saida para o DOS
MAIN ENDP
END MAIN
