.MODEL SMALL
.DATA
VETOR DB 1, 1, 1, 2, 2, 2
.CODE
MAIN PROC
MOV AX, @DATA
MOV DS,AX

CALL IMPRIME_VETOR ;CHAMA PROCEDIMEMENTO O QUAL IMPRIME OS ELEMENTOS DO VETOR

MOV AH,4CH
INT 21H ;saida para o DOS
MAIN ENDP


IMPRIME_VETOR PROC

    XOR DL, DL ;INICIA DL COMO 0
    MOV CX,6 ;INICIA CX COMO 6
    LEA SI, VETOR ;CARREGA O PRIMEIRO ENDEREÇO DO VETOR EM SI

    VOLTA:
    MOV DL, [SI] ;MOVE O ENDEREÇO DE SI PARA DL
    INC SI ;INCREMENTA O VALOR DE SI, PARA PERCORRER O VETOR
    ADD DL, 30H  ;CONVERTE O VALOR DE DL PARA ASCII


    MOV AH, 2 ;EXIBE O CARACTER EM DL
    INT 21H
    LOOP VOLTA ;LOOP ATÉ QUE CX SEJA 0

    RET

IMPRIME_VETOR ENDP
