.MODEL SMALL
.DATA
VETOR DB 1, 1, 1, 2, 2, 2
.CODE
MAIN PROC
    MOV AX, @DATA
    MOV DS,AX

    XOR DL, DL ;ZERA DL
    MOV CX,6 ;INICIA CONTADOR COMO 6 POIS VETOR TEM 6 POSIÇÕES
    LEA BX, VETOR ;CARREGA O ENDEREÇO INICIAL DO VETOR EM BX, LOGO A POSIÇÃO 0

    VOLTA:
    MOV DL, [BX] ;MOVE PARA DL O ENDEREÇO DE BX
    INC BX ;INCREMENTA VALOR DE BX
    ADD DL, 30H ;TRANSFORMA DE NÚMERO PARA ASCII

    MOV AH, 2
    INT 21H ;FUNÇÃO PARA IMPRIMIR 1 CARACTER

    LOOP VOLTA ;VOLTA ENQUANTO CX FOR MAIOR QUE 0


    MOV AH,4CH
    INT 21H ;saida para o DOS
MAIN ENDP
END MAIN
